const emojiDictionary = {
  happy: "😊",
  sad: "😢",
  love: "❤️",
  angry: "😡",
  party: "🎉",
  fire: "🔥",
  cool: "😎",
  smile: "😄",
  thumbs: "👍",
  star: "⭐",
  cry: "😭",
  laugh: "😂",
  heart: "💖",
  kiss: "😘",
  hug: "🤗",
  tired: "😴",
  shocked: "😱",
  sleepy: "😪",
  wow: "🤩",
  clap: "👏",
  idea: "💡",
  music: "🎵",
  rain: "🌧️",
  sun: "☀️",
  cloud: "☁️",
  coffee: "☕",
  tea: "🍵",
  dog: "🐶",
  cat: "🐱",
  car: "🚗",
  bike: "🚲",
  rocket: "🚀",
  cake: "🎂",
  gift: "🎁",
  computer: "💻",
  phone: "📱",
  money: "💰",
  tree: "🌳",
  flower: "🌸",
  moon: "🌙",
  starry: "🌟",
  rainbow: "🌈",
  book: "📚",
  writing: "✍️",
  graduation: "🎓",
  pin: "📌",
  thumbsdown: "👎",
  pizza: "🍕",
  burger: "🍔",
  fries: "🍟",
  sushi: "🍣",
  icecream: "🍦",
  drink: "🥤",
  soccer: "⚽",
  basketball: "🏀",
  cricket: "🏏",
  gaming: "🎮",
  sleep: "💤",
  angryface: "😠",
  robot: "🤖",
  alien: "👽",
  ghost: "👻",
  skull: "💀",
  sparkle: "✨",
  explosion: "💥",
  lion: "🦁",
  tiger: "🐯",
  bear: "🐻",
  panda: "🐼",
  monkey: "🐒",
  cow: "🐮",
  pig: "🐷",
  chicken: "🐔",
  rabbit: "🐰",
  frog: "🐸",
  fish: "🐟",
  dolphin: "🐬",
  whale: "🐳",
  shark: "🦈",
  octopus: "🐙",
  crab: "🦀",
  butterfly: "🦋",
  bee: "🐝",
  ant: "🐜",
  snail: "🐌",
  snake: "🐍",
  dragon: "🐉",
  cactus: "🌵",
  leaf: "🍃",
  mushroom: "🍄",
  apple: "🍎",
  banana: "🍌",
  grape: "🍇",
  cherry: "🍒",
  strawberry: "🍓",
  watermelon: "🍉",
  pineapple: "🍍",
  peach: "🍑",
  lemon: "🍋",
  carrot: "🥕",
  corn: "🌽",
  bread: "🍞",
  cheese: "🧀",
  hotdog: "🌭",
  taco: "🌮",
  burrito: "🌯",
  pasta: "🍝",
  donut: "🍩",
  cookie: "🍪",
  milk: "🥛",
  beer: "🍺",
  wine: "🍷",
  cocktail: "🍸",
  football: "🏈",
  tennis: "🎾",
  golf: "⛳",
  baseball: "⚾",
  hockey: "🏒",
  boxing: "🥊",
  skateboard: "🛹",
  bus: "🚍",
  train: "🚆",
  airplane: "✈️",
  ship: "🚢",
  house: "🏠",
  building: "🏢",
  hospital: "🏥",
  school: "🏫",
  store: "🏬",
  church: "⛪",
  castle: "🏰",
  tent: "⛺",
  factory: "🏭",
  bridge: "🌉",
  mountain: "🏔️",
  beach: "🏖️",
  desert: "🏜️",
  island: "🏝️",
  volcano: "🌋",
  forest: "🌲",
  city: "🌆",
  tv: "📺",
  camera: "📷",
  radio: "📻",
  clock: "⏰",
  lightbulb: "💡",
  tool: "🔧",
  hammer: "🔨",
  key: "🔑",
  lock: "🔒",
  calendar: "📅",
  notebook: "📓",
  envelope: "✉️",
  mailbox: "📬",
  hourglass: "⏳",
  firework: "🎆",
  umbrella: "☂️",
  clown: "🤡",
  bat: "🦇",
  spider: "🕷️",
  candy: "🍬",
  jackolantern: "🎃",
  snowman: "⛄",
  santa: "🎅",
  giftbox: "📦",
  carrotcake: "🥕🎂",
  gradcap: "🎓"
};
  
  /**
   * Translates a string into its emoji equivalent.
   * @param {string} text - The input string.
   * @returns {string} - The translated string with emojis.
   */
  function translateToEmoji(text) {
    if (typeof text !== "string") {
      throw new Error("Input must be a string");
    }
  
    const words = text.split(" ");
    const translatedWords = words.map((word) =>
      emojiDictionary[word.toLowerCase()] || word
    );
  
    return translatedWords.join(" ");
  }
  
  /**
   * Adds a new word-emoji mapping to the dictionary.
   * @param {string} word - The word to map.
   * @param {string} emoji - The emoji to map the word to.
   */
  function addEmoji(word, emoji) {
    if (typeof word !== "string" || typeof emoji !== "string") {
      throw new Error("Both word and emoji must be strings");
    }
  
    emojiDictionary[word.toLowerCase()] = emoji;
  }
  
  module.exports = {
    translateToEmoji,
    addEmoji,
  };
  